/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SschAmbulanceWlList {
    }
}
declare global {
    interface HTMLSschAmbulanceWlListElement extends Components.SschAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLSschAmbulanceWlListElement: {
        prototype: HTMLSschAmbulanceWlListElement;
        new (): HTMLSschAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "ssch-ambulance-wl-list": HTMLSschAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface SschAmbulanceWlList {
    }
    interface IntrinsicElements {
        "ssch-ambulance-wl-list": SschAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ssch-ambulance-wl-list": LocalJSX.SschAmbulanceWlList & JSXBase.HTMLAttributes<HTMLSschAmbulanceWlListElement>;
        }
    }
}
